name: CD


on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4

      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PARAPHRASE }}

        script: |
          echo "Changing Directory to Geometry-Jest"
          cd Geometry-Jest
          echo "Pulling From Github"
          git pull -q origin main
          echo "Git Pull Complete"
          echo "Rebuilding Frontend"
          cd frontend
          ../../.nvm/versions/node/v17.8.0/bin/npm ci
          ../../.nvm/versions/node/v17.8.0/bin/npm run build
          echo "Frontend Build Complete"
          cd ..
          echo "Starting Server"
          cd server
          ~/.cargo/bin/cargo build --release
